{
  "project_info": {
    "project_number": "692834500851",
    "project_id": "sales-app-922ec",
    "storage_bucket": "sales-app-922ec.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:692834500851:android:e6c404dd35ce4619407786",
        "android_client_info": {
          "package_name": "com.example.Sale_App"
        }
      },
      "oauth_client": [
        {
          "client_id": "692834500851-0lsn95dqlo1tlfquq89hkarf9itdsvfm.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "AIzaSyASCnIKwElP7JicEU5K-A9ojBteQiYlzac"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "692834500851-0lsn95dqlo1tlfquq89hkarf9itdsvfm.apps.googleusercontent.com",
              "client_type": 3
            }
          ]
        }
      }
    }
  ],
  "configuration_version": "1"
}
